import { Component } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import InputTodo from "../components/inputTodo";
import ListTodos from "../components/listTodos";

export default class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
      description: "",
    };
  }

  componentDidMount() {}

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Next To Do</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex">
          <h1 className="text-4xl my-6">Pern Todo</h1>
        </div>
        <InputTodo />
        <ListTodos />
      </div>
    );
  }
}
